Repository BC-MAY-21-RN/proyecto-final-proyecto-final-pf-f22-t2, pull requests merged in 2022-05, with the labels that each got.

#28 Created events screen, list
  TuristicApp/App.js
  TuristicApp/package-lock.json
  TuristicApp/src/library/utils/theme.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/EventsScreen/data.js
  TuristicApp/src/screens/EventsScreen/index.js
  TuristicApp/src/screens/EventsScreen/styled.js
  TuristicApp/src/screens/HomeScreen/index.js
Labels: review required

#33 22 connect all components v1
  TuristicApp/App.js
  TuristicApp/package-lock.json
  TuristicApp/src/components/Header-bar/index.js
  TuristicApp/src/components/Header-bar/styles.js
  TuristicApp/src/components/ModalEvents/index.js
  TuristicApp/src/components/ModalEvents/styled.js
  TuristicApp/src/components/MyInput/index.js
  TuristicApp/src/components/PlacesContent/indext.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/library/utils/theme.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/EventsScreen/index.js
  TuristicApp/src/screens/EventsScreen/styled.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/screens/PlacesScreen/index.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: mentor review required, review required

#35 Validation 25
  TuristicApp/src/components/Check/styles.js
  TuristicApp/src/components/MyButton/index.js
  TuristicApp/src/components/MyButton/styled.js
  TuristicApp/src/components/MyInput/index.js
  TuristicApp/src/components/MyInput/styled.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required

#39 Conect storage with placesscreen
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/assets/NO-IMAGE.png
  TuristicApp/src/assets/fondo.jpg
  TuristicApp/src/assets/fondo2.jpg
  TuristicApp/src/assets/fondo3.jpg
  TuristicApp/src/components/FormAddPlaces/index.js
  TuristicApp/src/components/FormInput/index.js
  TuristicApp/src/components/PlacesContent/index.js
  TuristicApp/src/components/UploadImage/index.js
  TuristicApp/src/components/UploadImage/styled.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/AddPlacesScreen/index.js
  TuristicApp/src/screens/AddPlacesScreen/services.js
  TuristicApp/src/screens/AddPlacesScreen/styled.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/services/addPlaces.js
Labels: review required

#46 Signin with google,
  TuristicApp/App.js
  TuristicApp/android/app/build.gradle
  TuristicApp/android/app/google-services.json
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: ready to merge

#47 Detail in place screen
  TuristicApp/src/components/Places/index.js
  TuristicApp/src/components/Places/styled.js
  TuristicApp/src/components/PlacesContent/index.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/AddPlacesScreen/services.js
  TuristicApp/src/screens/DetailsPlacesScreen/index.js
  TuristicApp/src/screens/DetailsPlacesScreen/styled.js
  TuristicApp/src/screens/PlacesScreen/index.js
  TuristicApp/src/services/addPlaces.js
Labels: review required

#55 Additional user info 51
  TuristicApp/src/components/FormInput/index.js
  TuristicApp/src/components/MyInput/index.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/UploadImage/index.js
  TuristicApp/src/components/UploadImage/styled.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/AddPlacesScreen/index.js
  TuristicApp/src/screens/AddUserScreen/index.js
  TuristicApp/src/screens/AddUserScreen/styled.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required

#56 Food screen 45
  TuristicApp/src/assets/img/arepitas.jpeg
  TuristicApp/src/assets/img/buñuelos.jpeg
  TuristicApp/src/assets/img/empanadas.jpeg
  TuristicApp/src/assets/img/envueltos.gif
  TuristicApp/src/assets/img/mazamorra.jpg
  TuristicApp/src/assets/img/pandebonos.jpeg
  TuristicApp/src/components/Carousel/CarouselCardItem.js
  TuristicApp/src/components/Carousel/CarouselCards.js
  TuristicApp/src/components/Carousel/data.js
  TuristicApp/src/components/Header-bar/index.js
  TuristicApp/src/components/Maps/index.js
  TuristicApp/src/components/ModalFood/index.js
  TuristicApp/src/components/ModalFood/styled.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/library/utils/theme.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/FoodScreen/data.js
  TuristicApp/src/screens/FoodScreen/index.js
  TuristicApp/src/screens/HomeScreen/index.js
Labels: review required

#57 Save the rate likes in the components (if they use it) 53
  TuristicApp/src/components/PlacesContent/index.js
  TuristicApp/src/components/Score/index.js
  TuristicApp/src/services/addPlaces.js
Labels: review required

#58 Create map points places 50
  TuristicApp/android/app/src/main/AndroidManifest.xml
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/components/ButtonPrimary/index.js
  TuristicApp/src/components/ButtonPrimary/styles.js
  TuristicApp/src/components/ButtonSecond/index.js
  TuristicApp/src/components/ButtonSecond/styles.js
  TuristicApp/src/components/FormAddPlaces/index.js
  TuristicApp/src/components/FormAddPlaces/styled.js
  TuristicApp/src/components/InputText/index.js
  TuristicApp/src/components/InputText/styles.js
  TuristicApp/src/components/MapLocation/index.js
  TuristicApp/src/components/MyButton/index.js
  TuristicApp/src/components/MyButton/styled.js
  TuristicApp/src/components/MyText/index.js
  TuristicApp/src/library/hooks/useMap.js
  TuristicApp/src/screens/AddPlacesScreen/index.js
  TuristicApp/src/screens/AddUserScreen/index.js
Labels: review required

#61 adding descriptions and photos in events
  TuristicApp/src/assets/img/50985367111_5ddeb7e70a_b.jpg
  TuristicApp/src/assets/img/ALGE2.jpg
  TuristicApp/src/assets/img/SANPEDRO.jpg
  TuristicApp/src/assets/img/Señora de lourdes.jpg
  TuristicApp/src/assets/img/fiestas-de-la-candelaria-2020_2622417_20200122125758.jpg
  TuristicApp/src/assets/img/iglesia-de-san-sebastian.jpg
  TuristicApp/src/assets/img/san antonio.jpg
  TuristicApp/src/assets/img/san pedro.jpeg
  TuristicApp/src/assets/img/sanantonio1.jpg
  TuristicApp/src/screens/EventsScreen/data.js
Labels: review required

#64 Refactor search bar component #54
  TuristicApp/src/components/Header-bar/index.js
  TuristicApp/src/components/Places/index.js
  TuristicApp/src/components/Score/index.js
  TuristicApp/src/components/Search/index.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/screens/PlacesScreen/index.js
  TuristicApp/src/screens/SearchScreen/index.js
Labels: review required

#65 Events/food connect with firebase#59
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/components/AddCalendar/index.js
  TuristicApp/src/components/FormAddEvent/index.js
  TuristicApp/src/components/FormAddEvent/styled.js
  TuristicApp/src/components/FormAddFood/index.js
  TuristicApp/src/components/FormAddFood/styled.js
  TuristicApp/src/components/FormAddPlace/index.js
  TuristicApp/src/components/FormAddPlace/styled.js
  TuristicApp/src/components/FormInput/index.js
  TuristicApp/src/components/MapLocation/index.js
  TuristicApp/src/components/ModalEvents/index.js
  TuristicApp/src/components/ModalFood/index.js
  TuristicApp/src/components/Places/index.js
  TuristicApp/src/components/Score/index.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/AddEventScreen/index.js
  TuristicApp/src/screens/AddEventScreen/styled.js
  TuristicApp/src/screens/AddFoodScreen/index.js
  TuristicApp/src/screens/AddFoodScreen/styled.js
  TuristicApp/src/screens/AddPlaceScreen/index.js
  TuristicApp/src/screens/AddPlaceScreen/styled.js
  TuristicApp/src/screens/AddUserScreen/index.js
  TuristicApp/src/screens/EventsScreen/index.js
  TuristicApp/src/screens/FoodScreen/index.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/screens/PlacesScreen/index.js
  TuristicApp/src/services/addPlaces.js
  TuristicApp/src/services/servicesEvent.js
  TuristicApp/src/services/servicesFood.js
  TuristicApp/src/services/servicesImage.js
  TuristicApp/src/services/servicesPlace.js
Labels: review required

#68 Rate screen (dislikes) 63
  TuristicApp/src/components/Score/index.js
  TuristicApp/src/services/servicesPlace.js
Labels: review required

#67 Create PoleDrirections Screen 41
  TuristicApp/src/assets/fondo_mano_del_gigante.jpg
  TuristicApp/src/assets/pole_directions.png
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/PoleDirectionScreen/index.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required

#66 Create profile screen 62
  TuristicApp/src/components/Header-bar/index.js
  TuristicApp/src/components/Logo/index.js
  TuristicApp/src/components/Logo/styled.js
  TuristicApp/src/components/Places/index.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/AddUserScreen/index.js
  TuristicApp/src/screens/AddUserScreen/styled.js
  TuristicApp/src/screens/DetailsPlacesScreen/index.js
  TuristicApp/src/screens/ProfileScreen/index.js
  TuristicApp/src/screens/ProfileScreen/styles.js
Labels: review required
