Repository BC-MAY-21-RN/proyecto-final-proyecto-final-pf-f22-t2, pull requests merged in 2022-04, with the labels that each got.

#3 Create SignUp Screen.
  TuristicApp/.eslintrc.js
  TuristicApp/App.js
  TuristicApp/android/app/build.gradle
  TuristicApp/android/settings.gradle
  TuristicApp/ios/Podfile.lock
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/components/ButtonPrimary/index.js
  TuristicApp/src/components/ButtonPrimary/styles.js
  TuristicApp/src/components/ButtonSecond/index.js
  TuristicApp/src/components/ButtonSecond/styles.js
  TuristicApp/src/components/Check/index.js
  TuristicApp/src/components/Check/styles.js
  TuristicApp/src/components/InputText/index.js
  TuristicApp/src/components/InputText/styles.js
  TuristicApp/src/library/utils/styledGlobal.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: mentor review required, review required

#8 Connect sign in & sign up
  TuristicApp/App.js
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/assets/logo-SignIn.png
  TuristicApp/src/components/Check/index.js
  TuristicApp/src/components/Check/styles.js
  TuristicApp/src/components/Footer/index.js
  TuristicApp/src/components/Logo/index.js
  TuristicApp/src/components/Logo/styled.js
  TuristicApp/src/components/MyButton/index.js
  TuristicApp/src/components/MyButton/styled.js
  TuristicApp/src/components/MyButton/styles.js
  TuristicApp/src/components/MyInput/index.js
  TuristicApp/src/components/MyInput/styled.js
  TuristicApp/src/components/MyText/index.js
  TuristicApp/src/library/utils/styledGlobal.js
  TuristicApp/src/library/utils/theme.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required

#9 Firebase conection, Auth, LogOut
  TuristicApp/android/app/build.gradle
  TuristicApp/android/app/google-services.json
  TuristicApp/android/build.gradle
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/components/MyButton/index.js
  TuristicApp/src/library/utils/auth.js
  TuristicApp/src/navigation/Navigation.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: ready to merge, review required

#15 Created component Places and fixes component Logo
  TuristicApp/src/assets/img/bathtub-outline.png
  TuristicApp/src/assets/img/imagen1.jpg
  TuristicApp/src/assets/img/imagen2.jpg
  TuristicApp/src/assets/img/imagen3.jpg
  TuristicApp/src/assets/img/imagen4.jpg
  TuristicApp/src/components/Logo/index.js
  TuristicApp/src/components/Places/data.js
  TuristicApp/src/components/Places/index.js
  TuristicApp/src/components/Places/styled.js
  TuristicApp/src/components/Score/index.js
  TuristicApp/src/components/Score/styled.js
  TuristicApp/src/library/utils/styledGlobal.js
  TuristicApp/src/screens/HomeScreen/index.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required

#18 Create HomeScreen
  TuristicApp/src/screens/HomeScreen/index.js
Labels: review required

#21 Create side screen menu #5
  TuristicApp/babel.config.js
  TuristicApp/ios/Podfile.lock
  TuristicApp/ios/TuristicApp/Info.plist
  TuristicApp/package-lock.json
  TuristicApp/package.json
  TuristicApp/src/assets/avatar.png
  TuristicApp/src/components/MyButton/styles.js
  TuristicApp/src/components/SideMenu/index.js
  TuristicApp/src/components/SideMenu/styles.js
  TuristicApp/src/library/utils/styledGlobal.js
  TuristicApp/src/screens/SignupScreen/index.js
Labels: review required
